# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Max Giron, Front-End Developer
email: maxgironcodes@icloud.com
description: Front-End Developer in Fort Worth, TX. I build web applications for brands and publish articles on HTML, CSS, JavaScript and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.maxgiron.codes" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: maxgironcodes
github_username: maxgironcodes

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _scss
permalink: /:title
incremental: false
